import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'esbuild';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourceDir = path.join(root, 'ui');
const outDir = path.join(root, 'public');

/** Modules esbuild folds into the bundle; the copies in `public/` are generated. */
const BUNDLED_MODULES = [
  'strabo.js',
  'strabo-core.js',
  'strabo-panels.js',
  'strabo-view.js',
  'strabo-viewport.js',
  'strabo-delegate.js',
  'strabo-selection.js',
  'strabo-float.js',
];

/**
 * Bundle the framework-free UI from `ui/` into the served `public/`.
 *
 * `public/` is the built artifact: `index.html` and `styles.css` are copied, and the ES
 * modules are bundled into `strabo.bundle.js`. Cytoscape stays a separate global script,
 * served from `node_modules` by the server, so it is not bundled. The output is not
 * minified, so a reviewer can read what is actually served.
 */
await build({
  entryPoints: [path.join(sourceDir, 'strabo.js')],
  outfile: path.join(outDir, 'strabo.bundle.js'),
  bundle: true,
  format: 'esm',
  target: ['es2020'],
  sourcemap: true,
  logLevel: 'warning',
  banner: { js: '/* Generated by scripts/build-ui.mjs from ui/ — do not edit. */' },
});

fs.copyFileSync(path.join(sourceDir, 'styles.css'), path.join(outDir, 'styles.css'));
fs.copyFileSync(path.join(sourceDir, 'index.html'), path.join(outDir, 'index.html'));
fs.copyFileSync(
  path.join(root, 'node_modules', '@xterm', 'xterm', 'css', 'xterm.css'),
  path.join(outDir, 'xterm.css'),
);

for (const name of BUNDLED_MODULES) {
  fs.rmSync(path.join(outDir, name), { force: true });
}

console.log(`[build-ui] bundled ui/ -> ${path.relative(root, path.join(outDir, 'strabo.bundle.js'))}`);
