import { Router } from 'express';

import { listBranches } from '../../analysis/branches.ts';
import { fetchBranches, pullBranch, pushBranch, syncBranch } from '../../analysis/branch-actions.ts';
import { commitWorkingTree } from '../../analysis/commit.ts';
import { isSameOriginRequest, sendError } from '../http.ts';
import type { AnalysisContext } from './analysis-context.ts';

/** Branch listing and the state-changing Git actions. */
export function createGitRouter(context: AnalysisContext): Router {
  const router = Router();
  const { resolve } = context;

  /**
   * Branches with their upstream sync and their divergence from a base branch. `base`
   * names the branch to compare with; by default the remote's default branch.
   */
  router.get('/analysis/branches', async (request, response) => {
    try {
      const repository = resolve(request);
      const base = typeof request.query.base === 'string' && request.query.base ? request.query.base : undefined;
      response.json(await listBranches(repository.root, base));
    } catch (error) {
      sendError(response, error);
    }
  });

  /**
   * Git actions that write: fetch, pull (fetch + fast-forward), push, and sync. They are
   * state-changing, so they are accepted only from the Strabo page's own origin (see
   * `isSameOriginRequest`), and the analysis module validates every ref before it reaches Git
   * and never force-pushes.
   */
  router.post('/analysis/branches/fetch', async (request, response) => {
    try {
      if (!isSameOriginRequest(request)) {
        response.status(403).json({ error: 'branch actions are accepted only from the Strabo page.' });
        return;
      }
      const repository = resolve(request);
      const remote = typeof request.body?.remote === 'string' && request.body.remote ? request.body.remote : undefined;
      response.json(await fetchBranches(repository.root, remote));
    } catch (error) {
      sendError(response, error);
    }
  });

  router.post('/analysis/branches/push', async (request, response) => {
    try {
      if (!isSameOriginRequest(request)) {
        response.status(403).json({ error: 'branch actions are accepted only from the Strabo page.' });
        return;
      }
      const repository = resolve(request);
      const branch = typeof request.body?.branch === 'string' ? request.body.branch : '';
      if (!branch) {
        response.status(400).json({ error: 'branch is required.' });
        return;
      }
      response.json(await pushBranch(repository.root, branch));
    } catch (error) {
      sendError(response, error);
    }
  });

  router.post('/analysis/branches/pull', async (request, response) => {
    try {
      if (!isSameOriginRequest(request)) {
        response.status(403).json({ error: 'branch actions are accepted only from the Strabo page.' });
        return;
      }
      const repository = resolve(request);
      const branch = typeof request.body?.branch === 'string' ? request.body.branch : '';
      if (!branch) {
        response.status(400).json({ error: 'branch is required.' });
        return;
      }
      response.json(await pullBranch(repository.root, branch));
    } catch (error) {
      sendError(response, error);
    }
  });

  router.post('/analysis/branches/sync', async (request, response) => {
    try {
      if (!isSameOriginRequest(request)) {
        response.status(403).json({ error: 'branch actions are accepted only from the Strabo page.' });
        return;
      }
      const repository = resolve(request);
      const branch = typeof request.body?.branch === 'string' ? request.body.branch : '';
      if (!branch) {
        response.status(400).json({ error: 'branch is required.' });
        return;
      }
      response.json(await syncBranch(repository.root, branch));
    } catch (error) {
      sendError(response, error);
    }
  });

  /**
   * Commit the working tree and push the current branch, from a message the operator
   * confirmed in the browser.
   *
   * State-changing, so it is accepted only from the Strabo page's own origin. The message
   * reaches Git as a `-m` argument, never a shell, and the push is a normal push — never
   * forced — so a diverged branch is reported after the commit is made rather than
   * overwritten. The message is generated by `POST /narrator/commit-message`, but this route
   * takes whatever the operator submitted and does not contact the narrator itself.
   */
  router.post('/analysis/commit', async (request, response) => {
    try {
      if (!isSameOriginRequest(request)) {
        response.status(403).json({ error: 'commits are accepted only from the Strabo page.' });
        return;
      }
      const repository = resolve(request);
      const message = typeof request.body?.message === 'string' ? request.body.message : '';
      const push = request.body?.push !== false;
      response.json(await commitWorkingTree(repository.root, message, { push }));
    } catch (error) {
      sendError(response, error);
    }
  });

  return router;
}
